<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_directmail_plaintext"
 *
 * Auto generated by Extension Builder 2015-10-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Advanced plain text for Direct Mail',
	'description' => 'Advanced plain text rendering for Direct Mail',
	'category' => 'templates',
	'author' => 'Jonathan Heilmann',
	'author_email' => 'mail@jonathan-heilmann.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1-dev',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
			'direct_mail' => '4.0.1',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);